apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-api
  template:
    metadata:
      labels:
        app: email-api
    spec:
      containers:
        - name: email-api
          image: thesaurus5689/email-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: gemini-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: email-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: email-api
