apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-frontend
  template:
    metadata:
      labels:
        app: email-frontend
    spec:
      containers:
        - name: email-frontend
          image: thesaurus5689/email-frontend:latest # Added :latest tag
          imagePullPolicy: Always
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: email-frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP
  selector:
    app: email-frontend # This matches your deployment's labels
